### ISSUE TITLE
Copy to pasteboard when exporting

### ISSUE THREAD

**Issue by stig** [stig/ox-jira.el#12]
It's nice to have the new buffer created so you can eyeball the output, but it would be nice if the output would also be added to the system pasteboard (and perhaps the kill ring) so that I don't have to do `C-x h M-w` first immediately after the export to get it into my paste buffer.

**Comment by baron42bba** [comment]
Hi stig!
Create a keyboard macro, name it and save it. Just like I did: https://github.com/baron42bba/.emacs.d/commit/00f45007e0e85b9e654cf008b88e5b74637469aa
I remove the header as it is the title of our tickets.

**Comment by stig** [comment]
I found that I could set org-mode to copy to kill-ring if running interactively like this:

``` emacs-lisp
  (setq org-export-copy-to-kill-ring 'if-interactive)
```

It does mean that it happens for all languages, which is not ideal but acceptable in my case. It also doesn't have your trick of omitting the header, but it sufficient for me.
