### ISSUE TITLE
Support horizontal rule

### ISSUE THREAD

**Issue by Munsen** [stig/ox-jira.el#15]
It seem to be not support horizontal rule.

org-mode export horizontal rule at least five hyphen
http://orgmode.org/manual/Horizontal-rules.html
`-----`

jira has same thing. four hyphen
https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=breaks
`----`

thanks

**Comment by stig** [comment]
Oops, I missed this issue. Thanks for reporting! I would be happy to add this. Do you fancy taking a stab at adding this yourself? It should be relatively easy to create a test case by looking in the `tests/ox-jira-tests.org` file. Even a failing test case would help :-)

**Comment by Munsen** [comment]
Ok. I created pull-request #16 . I'm sure it works. but I don't know emacs-lisp well.

**Comment by stig** [comment]
This was closed by #16. Thanks @Munsen!
