### ISSUE TITLE
Enhance Source Block Metadata

### ISSUE THREAD

**Issue by rymndhng** [stig/ox-jira.el#30]
I have two feature requests to make code blocks a little nicer to work with.

1. Add support for using `#+NAME` as src block titles
2. Add the ability to set collapse=true if the number of lines is greater than a predefined threshold.

**Comment by rymndhng** [comment]
I can start a PR for this if you'd like, (I have a prototype, but am also new to plugin development).

EDIT: created PR

**Comment by stig** [comment]
Closed by #31
