### ISSUE TITLE
Snake case words are treated as a special syntax

### ISSUE THREAD

**Issue by natecox** [stig/ox-jira.el#53]
### Problem
When exporting any text containing snake_cased words (common in development, devops, etc) a special syntax seems to be applied.

### Example
if I have text which looks like this:
```
this_is_a_test
```

it gets exported to look like this:
```
this{anchor}~is~{anchor}~a~{anchor}~test~
```

and is rendered by jira like this:
![image](https://user-images.githubusercontent.com/2782695/91609138-b4898b80-e92b-11ea-9184-7720bedc0fa4.png)

### Followup
I'm not sure what is triggering this syntax, but if this is expected behavior is there also an intended workaround?

I know that I can use `verbatim` (i.e., `=this_is_a_test=`) to bypass the problem, but I don't necessarily want monospaced text in all circumstances.

**Comment by natecox** [comment]
looks like I can just add `#+options: ^:nil` to the document header and it will turn off super/subscript. That's adequate for me.

**Comment by stig** [comment]
You're right that this is annoying though. I keep forgetting about it myself, and I use snake-case in identifiers _a lot more_ than I use it for subscript/superscript. I wonder if the default can be flipped?

**Comment by natecox** [comment]
So I've looked for a way to change the default here and haven't found much luck. What I ended up doing was adding `#+options: ^:nil` to my setup file and just including it with all of my org mode docs via `#+setupfile: setupfile.org`. 

I still have to remember to actually add the setup file, but it's more likely that I'll include than than remember to turn superscript off. I'm still trying to find a way to add that setup file to all org docs by default.

edit to include: my next step here is adding something for [auto-insert-mode](https://www.emacswiki.org/emacs/AutoInsertMode) to do this for me.

**Comment by stig** [comment]
I just looked into this a little bit, and found that if you use `#+options: ^:{}` you can still use `a_{b}` to get a subscript, but `a_b` will be a literal underscore. You can also set `org-export-with-sub-superscripts` to `{}` to get this effect. (Or make that variable `nil` to turn off special handling completely.)

I'm considering make `{}` the default for ox-jira.el -- if it's not too much effort :-) 
(I don't know how to go about it yet.)

**Comment by stig** [comment]
While mulling it over, I'm putting this in my config: `(setq org-export-with-sub-superscripts '{})`.

**Comment by natecox** [comment]
Oh good catch on the curly braces there, I hadn't seen that. I'll be setting my default to that as well.
