### ISSUE TITLE
The option to export to JIRA does not appear in the Export Dispatcher since update

### ISSUE THREAD

**Issue by paraschivescu** [stig/ox-jira.el#56]
Using
GNU Emacs 27.1 (build 1, x86_64-w64-mingw32)
ox-jira 20200920.1119

The option to export to JIRA no longer appears in the Export Dispatcher.

**Comment by stig** [comment]
I think there's potentially a change in Org that means you need to load the module before it shows up...? Can you please do `M-x load-library RET ox-jira RET` and try exporting again?

**Comment by paraschivescu** [comment]
Yup, that did it. Thanks!
